lang: en
timezone: Africa/Tunis
title: Cyber Security By Sahnoun111
tagline: Cyber Security Expert | Hacker at Heart | Passionate Learner | 🇹🇳  
description: >-
  A deep dive into my journey through the world of cybersecurity, hacking, and digital defense. 
  From personal experiments in malware analysis, and log forensics, to professional insights into pentesting, vulnerability research, and AI security. 
  Expect a mix of hands-on labs, tool reviews, threat hunting techniques, and my reflections on the evolving cyber landscape.
url: "https://sahnoun111.io"
github:
  username: sahnoun111 
X:
  username: Sahnounoussama5
social:
  name: Cyber Security By Sahnoun111
  links:
    - https://x.com/Sahnounoussama5
    - https://github.com/sahnoun11
    - https://www.linkedin.com/in/oussama-sahnoun-0ba565131/
    - https://www.youtube.com/@Sahnoun111
